### ISSUE TITLE
Readme viết như cái đb đọc khó vcl viết lại đi nhé

### ISSUE THREAD

**Issue by DatNguyen2711** [vnch/vnch.github.io#4]

**Comment by DatNguyen2711** [comment]
![333sd](https://github.com/vnch/vnch.github.io/assets/81822483/b6a29072-cc35-42ea-9c75-7b87e7f9652f)

**Comment by Backycho** [comment]
@DatNguyen2711 Chết mẹ mày nha con ! https://www.facebook.com/MrDatDepZai 
![image](https://github.com/vnch/vnch.github.io/assets/161861930/97f0abdf-02c2-4842-84ae-a36dcb5aaf69)

**Comment by DatNguyen2711** [comment]
mày ngu như 1 con chó luôn facebook để lù lù ra còn tìm sai loại não chó như này chết bố ỉa vào quan tài :))

**Comment by DatNguyen2711** [comment]
> Để tao viết lại cho mày nè thằng lồn @DatNguyen2711 ![image](https://private-user-images.githubusercontent.com/161861930/309314951-70e80804-b124-451e-a4c8-eef810d7016d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTEzOTQsIm5iZiI6MTcwOTM5MTA5NCwicGF0aCI6Ii8xNjE4NjE5MzAvMzA5MzE0OTUxLTcwZTgwODA0LWIxMjQtNDUxZS1hNGM4LWVlZjgxMGQ3MDE2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxNDUxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wODcyZDhiNjM2NWVkYmE2NzIxYjBkZTUyZmQ2MjcxNzE3MDI2NjRiZDFlYzY5ODBlMzJkZDkzMDg4ZTU4YmM4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.og8LotFpWHF-pS_LYlvm7CfuvP5U3BV5CuTUfbyudww

> @DatNguyen2711 Chết mẹ mày nha con ! https://www.facebook.com/MrDatDepZai ![image](https://private-user-images.githubusercontent.com/161861930/309467850-97f0abdf-02c2-4842-84ae-a36dcb5aaf69.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkzOTEzOTQsIm5iZiI6MTcwOTM5MTA5NCwicGF0aCI6Ii8xNjE4NjE5MzAvMzA5NDY3ODUwLTk3ZjBhYmRmLTAyYzItNDg0Mi04NGFlLWEzNmRjYjVhYWY2OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzAyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMwMlQxNDUxMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNDEwMDUwNjdjMGU5ZTc4MmI4ZDdkMzZiN2VkNjMxZjk1MDM3NjY2NWI0NmI1NzFiMDM3NTU2NjcxMTMyZWZlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.lDufbuLt35IlgLWo0X_xOjTFGIbDcI4tdQFfdFRGmvM)

sao mày ngu thế địt mẹ mày luôn facebook để hẳn cái link tìm còn sai ăn hại như con chó
