### ISSUE TITLE
COn chó kia ra bố mày đút xương cho mà ăn

### ISSUE THREAD

**Issue by DatNguyen2711** [vnch/vnch.github.io#9]
![image](https://github.com/vnch/vnch.github.io/assets/81822483/d4b754f2-f5bb-424d-ac10-15012933d345)
địt mẹ con chó ngu kia đâu tìm facebook ngu như mày thì chết đi sống làm con cặc gì

**Comment by Backycho** [comment]
@DatNguyen2711 Thằng hèn óc cặc ẩn public repo rồi à. Đúng là Bắc Kỳ chó hèn như chó haha

**Comment by DatNguyen2711** [comment]
đối phó với mày dễ ẹc mà :))))))) dùng vài trò là xong rồi chứ đéo ai ngu như con chó để hẳn link fb tìm còn sai

**Comment by DatNguyen2711** [comment]
> @DatNguyen2711 Thằng hèn óc cặc ẩn public repo rồi à. Đúng là Bắc Kỳ chó hèn như chó haha

có mỗi việc click vào cái link fb của bố mày còn đéo xong thì chưa đủ tuổi đâu con ạ :))))) may quá dễ đối phó mấy thằng 3/// hóa ra con chó nào cũng ngu như nhau

**Comment by DatNguyen2711** [comment]
cái địt mẹ con chó ngu ném cho cục xương vào tận mõm còn đớp trượt thì chết con bà nhà mày đi
